{
    'name': 'JetMaster Website Customizations',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'version': '13.0.0.8',
    'website': 'https://www.pragtech.co.in',
    'summary': 'Jetmaster website customizations',
    'depends': ['website_sale', 'product', 'website_blog', 'sale_management','mrp'],
    'description': '',
    'data': [
        'security/ir.model.access.csv',
        'views/website_templates/direct_vent_flue_systems_view.xml',
        'views/website_templates/brochures_specifications_view.xml',
        'views/website_templates/book_a_service_view.xml',
        'views/website_templates/contact_us_view.xml',
        'views/website_templates/products_page_view.xml',
        'views/website_templates/gallery_view.xml',
        'views/website_templates/resources_view.xml',
        'views/website_templates/product_enquiry_template.xml',
        'views/website_templates/homepage.xml',
        'views/website_templates/dealers_page.xml',
        'data/website_menus.xml',
        'views/product_view.xml',
        'views/gallery_view.xml',
        'views/booking_service_view.xml',
#         'views/contact_details_view.xml',
        'views/res_partner_view.xml',
        'views/res_config_settings_view.xml',
        'views/templates.xml',
#         'views/mrp_bom_view.xml',
    ],
    'live_test_url': '',
    # 'qweb': ['static/src/xml/*.xml'],
    # 'currency': 'EUR',
    # 'license': 'OPL-1',
    'installable': True,
    'application': True,
    'auto_install': False,
}
